# Generated by Django 5.1.1 on 2024-10-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('courier', 'Courier'), ('admin', 'Admin')], default='client', max_length=10),
        ),
    ]
