# Generated by Django 5.1.1 on 2024-10-29 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_last_name_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Введите телефон в формате +7(XXX) XXX-XX-XX', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть в формате: +7(XXX) XXX-XX-XX', regex='^\\+7\\(\\d{3}\\)\\d{3}-\\d{2}-\\d{2}$')]),
        ),
    ]
