# Generated by Django 5.1.1 on 2024-12-10 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/%Y/%m/', verbose_name='Фото профиля'),
        ),
    ]
