# Generated by Django 5.1.1 on 2024-11-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_address_order_street_order_building_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(default='Москва', max_length=100),
        ),
    ]
