# Generated by Django 5.1.1 on 2024-11-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('awaiting_courier', 'Ожидает назначения курьера'), ('courier_on_the_way', 'Курьер в пути'), ('at_location', 'На месте выполнения'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('return', 'Возврат')], default='pending', max_length=50),
        ),
    ]
