# Generated by Django 5.1.1 on 2024-12-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('courier_assigned', 'Курьер назначен'), ('courier_on_the_way', 'Курьер в пути'), ('at_location', 'На месте выполнения'), ('courier_on_the_way_to_master', 'Курьер в пути к мастеру'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('cancelled', 'Отменен'), ('return', 'Возврат')], default='pending', max_length=50),
        ),
    ]
