# Generated by Django 5.1.1 on 2024-12-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
