# Generated by Django 4.2 on 2024-12-10 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_order', 'Новый заказ'), ('courier_assigned', 'Курьер назначен'), ('courier_on_the_way', 'Курьер в пути'), ('at_location', 'Курьер на месте'), ('courier_on_the_way_to_master', 'Курьер везет заказ мастеру'), ('in_progress', 'Заказ в работе у мастера'), ('completed', 'Заказ выполнен'), ('cancelled', 'Заказ отменен'), ('return', 'Возврат заказа'), ('system', 'Системное уведомление')], max_length=50),
        ),
    ]
